# Generated by Django 3.0.1 on 2019-12-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank='True', upload_to='profile_image'),
        ),
    ]
