# Generated by Django 3.0.1 on 2019-12-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_classroom_code'),
    ]

    operations = [
    ]
