# Generated by Django 3.0.1 on 2019-12-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20191231_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notes_heading',
            field=models.CharField(default='Notes Topic', max_length=200),
        ),
    ]
