# Generated by Django 3.0.1 on 2020-01-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_assignment_assignmentanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_heading',
            field=models.CharField(default='Assignment Topic', max_length=200),
        ),
    ]
