# Generated by Django 3.0.1 on 2020-01-01 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20200101_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentanswers',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='classroom.Assignment'),
        ),
    ]
