# Generated by Django 3.0.1 on 2020-01-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_image'),
        ('classroom', '0010_auto_20200101_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentanswers',
            name='student',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.Student'),
            preserve_default=False,
        ),
    ]
